package typeusage.tests;

public class ExpectedResult {
    static String VALUE = "[location:CallMethodOnThis:6 context:<init>() type:CallMethodOnThis call:<init>() extend:CallMethodO"
            + "nThis, location:CallMethodOnThis:11 context:context() type:CallMethodOnThis call:test7() extend:Call"
            + "MethodOnThis, location:TypeUsageTestData:3 context:<init>() type:TypeUsageTestData call:<init>() ext"
            + "end:TypeUsageTestData, location:Main:58 context:<init>() type:Main call:<init>() extend:Main, locati"
            + "on:Main:67 context:context(MethodParameter,int) type:MethodParameter call:test2() call:test1() exten"
            + "d:MethodParameter, location:Main:71 context:context(MethodParameter,int) type:LocalVariable call:<in"
            + "it>() call:cee() call:test3() extend:LocalVariable, location:Main:77 context:context(MethodParameter"
            + ",int) type:Inheritance call:<init>() call:cee() call:test3() extend:Inheritance extend:A, location:M"
            + "ain:83 context:context(MethodParameter,int) type:Field call:foo() call:test4() extend:Field, locatio"
            + "n:Main:85 context:context(MethodParameter,int) type:Field42 call:test42() call:foo42() extend:Field4"
            + "2, location:Main:98 context:context2(MethodParameter,int) type:A call:test3() extend:A, location:Mai"
            + "n:113 context:toto() type:java.lang.Object call:<init>() call:hashCode() , location:Main:115 context"
            + ":toto() type:java.lang.String call:substring() extend:java.lang.String, location:Main:118 context:to"
            + "to() type:java.lang.Object call:notify() call:getClass() , location:Main:120 context:toto() type:jav"
            + "a.lang.String call:matches() extend:java.lang.String, location:A:48 context:<init>() type:A call:<in"
            + "it>() extend:A, location:Inheritance:53 context:<init>() type:Inheritance call:<init>() extend:Inher"
            + "itance extend:A, location:LocalVariable:24 context:<init>() type:LocalVariable call:<init>() extend:"
            + "LocalVariable, location:Field:32 context:<init>() type:Field call:<init>() extend:Field, location:ty"
            + "peusage.tests.ExpectedResult:3 context:<init>() type:typeusage.tests.ExpectedResult call:<init>() ex"
            + "tend:typeusage.tests.ExpectedResult, location:typeusage.tests.TestTypeUsageCollector:12 context:<ini"
            + "t>() type:typeusage.tests.TestTypeUsageCollector call:<init>() extend:typeusage.tests.TestTypeUsageC"
            + "ollector extend:typeusage.miner.TypeUsageCollector, location:typeusage.tests.TestTypeUsageCollector:"
            + "15 context:<init>() type:java.util.ArrayList call:<init>() extend:java.util.ArrayList extend:java.ut"
            + "il.AbstractCollection extend:java.util.AbstractList, location:typeusage.tests.TestTypeUsageCollector"
            + ":19 context:receive(TypeUsage) type:java.util.List call:add() call:contains() call:toString() extend"
            + ":java.util.List, location:typeusage.tests.TestTypeUsage:5 context:<init>() type:typeusage.tests.Test"
            + "TypeUsage call:<init>() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, locat"
            + "ion:typeusage.tests.TestTypeUsage:13 context:call(String) type:java.lang.StringBuilder call:<init>()"
            + " call:append() extend:java.lang.AbstractStringBuilder extend:java.lang.StringBuilder, location:typeu"
            + "sage.tests.TestTypeUsage:13 context:call(String) type:java.lang.StringBuilder call:toString() extend"
            + ":java.lang.AbstractStringBuilder extend:java.lang.StringBuilder, location:typeusage.tests.TestTypeUs"
            + "age:13 context:call(String) type:java.util.Set call:add() extend:java.util.Set, location:typeusage.t"
            + "ests.Tests:16 context:<init>() type:typeusage.tests.Tests call:<init>() extend:typeusage.tests.Tests"
            + ", location:typeusage.tests.Tests:22 context:setup() type:typeusage.tests.TestTypeUsageCollector call"
            + ":<init>() extend:typeusage.tests.TestTypeUsageCollector extend:typeusage.miner.TypeUsageCollector, l"
            + "ocation:typeusage.tests.Tests:23 context:setup() type:typeusage.tests.TestTypeUsageCollector call:se"
            + "tDirToProcess() extend:typeusage.tests.TestTypeUsageCollector extend:typeusage.miner.TypeUsageCollec"
            + "tor, location:typeusage.tests.Tests:24 context:setup() type:typeusage.tests.TestTypeUsageCollector c"
            + "all:run() extend:typeusage.tests.TestTypeUsageCollector extend:typeusage.miner.TypeUsageCollector, l"
            + "ocation:typeusage.tests.Tests:29 context:tu() type:typeusage.tests.TestTypeUsage call:<init>() exten"
            + "d:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:34 "
            + "context:testCallingMethodOnThis() type:typeusage.tests.Tests call:tu() extend:typeusage.tests.Tests,"
            + " location:typeusage.tests.Tests:34 context:testCallingMethodOnThis() type:typeusage.tests.TestTypeUs"
            + "age call:type() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:type"
            + "usage.tests.Tests:34 context:testCallingMethodOnThis() type:typeusage.tests.TestTypeUsage call:call("
            + ") extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Te"
            + "sts:41 context:testCallingMethodOnNull() type:typeusage.tests.Tests call:tu() extend:typeusage.tests"
            + ".Tests, location:typeusage.tests.Tests:41 context:testCallingMethodOnNull() type:typeusage.tests.Tes"
            + "tTypeUsage call:type() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, locati"
            + "on:typeusage.tests.Tests:41 context:testCallingMethodOnNull() type:typeusage.tests.TestTypeUsage cal"
            + "l:call() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.t"
            + "ests.Tests:46 context:testCallingMethodOnMethodParameter() type:typeusage.tests.Tests call:tu() exte"
            + "nd:typeusage.tests.Tests, location:typeusage.tests.Tests:46 context:testCallingMethodOnMethodParamet"
            + "er() type:typeusage.tests.TestTypeUsage call:type() extend:typeusage.miner.TypeUsage extend:typeusag"
            + "e.tests.TestTypeUsage, location:typeusage.tests.Tests:46 context:testCallingMethodOnMethodParameter("
            + ") type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.TypeUsage extend:typeusage.t"
            + "ests.TestTypeUsage, location:typeusage.tests.Tests:46 context:testCallingMethodOnMethodParameter() t"
            + "ype:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.TypeUsage extend:typeusage.test"
            + "s.TestTypeUsage, location:typeusage.tests.Tests:51 context:testCallingMethodOnLocalVariable() type:t"
            + "ypeusage.tests.Tests call:tu() extend:typeusage.tests.Tests, location:typeusage.tests.Tests:51 conte"
            + "xt:testCallingMethodOnLocalVariable() type:typeusage.tests.TestTypeUsage call:type() extend:typeusag"
            + "e.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:51 context:te"
            + "stCallingMethodOnLocalVariable() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.min"
            + "er.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:51 context:testCal"
            + "lingMethodOnLocalVariable() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.Ty"
            + "peUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:51 context:testCallingM"
            + "ethodOnLocalVariable() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.TypeUsa"
            + "ge extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:56 context:testTypeUsageWith"
            + "Inheritance() type:typeusage.tests.Tests call:tu() extend:typeusage.tests.Tests, location:typeusage."
            + "tests.Tests:56 context:testTypeUsageWithInheritance() type:typeusage.tests.TestTypeUsage call:type()"
            + " extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tes"
            + "ts:56 context:testTypeUsageWithInheritance() type:typeusage.tests.TestTypeUsage call:call() extend:t"
            + "ypeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:56 con"
            + "text:testTypeUsageWithInheritance() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage."
            + "miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:56 context:test"
            + "TypeUsageWithInheritance() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.Typ"
            + "eUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:62 context:testTypeUsage"
            + "Field() type:typeusage.tests.Tests call:tu() extend:typeusage.tests.Tests, location:typeusage.tests."
            + "Tests:62 context:testTypeUsageField() type:typeusage.tests.TestTypeUsage call:type() extend:typeusag"
            + "e.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:62 context:te"
            + "stTypeUsageField() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.TypeUsage e"
            + "xtend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:62 context:testTypeUsageField() "
            + "type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.TypeUsage extend:typeusage.tes"
            + "ts.TestTypeUsage, location:typeusage.tests.Tests:65 context:testTypeUsageField() type:typeusage.test"
            + "s.TestTypeUsage call:type() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, l"
            + "ocation:typeusage.tests.Tests:65 context:testTypeUsageField() type:typeusage.tests.TestTypeUsage cal"
            + "l:call() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.t"
            + "ests.Tests:65 context:testTypeUsageField() type:typeusage.tests.TestTypeUsage call:call() extend:typ"
            + "eusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:71 conte"
            + "xt:testTypeUsageCast() type:typeusage.tests.Tests call:tu() extend:typeusage.tests.Tests, location:t"
            + "ypeusage.tests.Tests:71 context:testTypeUsageCast() type:typeusage.tests.TestTypeUsage call:type() e"
            + "xtend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests"
            + ":71 context:testTypeUsageCast() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.mine"
            + "r.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:71 context:testType"
            + "UsageCast() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.TypeUsage extend:t"
            + "ypeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:72 context:testTypeUsageCast() type:typ"
            + "eusage.tests.TestTypeUsage call:type() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestT"
            + "ypeUsage, location:typeusage.tests.Tests:72 context:testTypeUsageCast() type:typeusage.tests.TestTyp"
            + "eUsage call:call() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:t"
            + "ypeusage.tests.Tests:74 context:testTypeUsageCast() type:typeusage.tests.TestTypeUsage call:type() e"
            + "xtend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests"
            + ":74 context:testTypeUsageCast() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.mine"
            + "r.TypeUsage extend:typeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:74 context:testType"
            + "UsageCast() type:typeusage.tests.TestTypeUsage call:call() extend:typeusage.miner.TypeUsage extend:t"
            + "ypeusage.tests.TestTypeUsage, location:typeusage.tests.Tests:75 context:testTypeUsageCast() type:typ"
            + "eusage.tests.TestTypeUsage call:type() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestT"
            + "ypeUsage, location:typeusage.tests.Tests:75 context:testTypeUsageCast() type:typeusage.tests.TestTyp"
            + "eUsage call:call() extend:typeusage.miner.TypeUsage extend:typeusage.tests.TestTypeUsage, location:t"
            + "ypeusage.tests.Tests:81 context:after() type:java.io.PrintStream call:println() extend:java.io.Outpu"
            + "tStream extend:java.io.PrintStream extend:java.io.FilterOutputStream, location:typeusage.tests.Tests"
            + ":82 context:after() type:java.io.PrintStream call:println() extend:java.io.OutputStream extend:java."
            + "io.PrintStream extend:java.io.FilterOutputStream, location:MethodParameter:15 context:<init>() type:"
            + "MethodParameter call:<init>() extend:MethodParameter, location:Field42:40 context:<init>() type:Fiel"
            + "d42 call:<init>() extend:Field42]";
}